twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ga_tracker_id: "%ga_tracker_id%"
        website_link: "%website_link%"
        player_link: "%player_link%"
        bot_link: "%bot_link%"
        track_endpoint: "%track_endpoint%"