twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        ga_tracker_id: "%ga_tracker_id%"
        website_link: "%website_link%"
        player_link: "%player_link%"
        bot_link: "%bot_link%"
        track_endpoint: "%track_endpoint%"